BowlingLeagueApp/Models/Bowler.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BowlingLeagueApp.Models
{
    public class Bowler
    {
        [Key]
        [Required]
        public int BowlerID { get; set; }
        [Required]
        public string BowlerLastName { get; set; }
        [Required]
        public string BowlerFirstName { get; set; }
        [MaxLength(1)]
        public string BowlerMiddleInit { get; set; }
        [Required]
        public string BowlerAddress { get; set; }
        [Required]
        public string BowlerCity { get; set; }
        [Required]
        [MaxLength(2)]
        public string BowlerState { get; set; }
        [Required]
        public string BowlerZip { get; set; }
        [Required]
        public string BowlerPhoneNumber { get; set; }
        public int TeamID { get; set; }
        public Team Team { get; set; }
    }
}

BowlingLeagueApp/Models/BowlersDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BowlingLeagueApp.Models
{
    public class BowlersDbContext : DbContext
    {
        public BowlersDbContext(DbContextOptions<BowlersDbContext> options) : base(options)
        {

        }

        public DbSet<Bowler> Bowlers { get; set; }
        public DbSet<Team> Teams { get; set; }
    }
}

BowlingLeagueApp/Models/EFBowlersRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BowlingLeagueApp.Models
{
    public class EFBowlersRepository : IBowlersRepository
    {
        private BowlersDbContext _context { get; set; }

        public EFBowlersRepository(BowlersDbContext temp)
        {
            _context = temp;
        }

        public IQueryable<Bowler> Bowlers => _context.Bowlers;
    }
}

BowlingLeagueApp/Models/IBowlersRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BowlingLeagueApp.Models
{
    public interface IBowlersRepository
    {
        IQueryable<Bowler> Bowlers { get; }
    }
}

BowlingLeagueApp/Models/Team.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BowlingLeagueApp.Models
{
    public class Team
    {
        [Key]
        [Required]
        public int TeamID { get; set; }
        [Required]
        public string TeamName { get; set; }
        [Required]
        public int CaptainID { get; set; }
    }
}

BowlingLeagueApp/Components/TeamsViewComponent.cs
using BowlingLeagueApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BowlingLeagueApp.Components
{
    public class TeamsViewComponent : ViewComponent
    {
        private BowlersDbContext _context { get; set; }

        public TeamsViewComponent(BowlersDbContext temp)
        {
            _context = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedTeam = RouteData?.Values["team"];

            var teams = _context.Bowlers
                .Select(x => x.Team.TeamName)
                .Distinct()
                .OrderBy(x => x);

            return View(teams);
        }
    }
}

BowlingLeagueApp/Controllers/HomeController.cs
using BowlingLeagueApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BowlingLeagueApp.Controllers
{
    public class HomeController : Controller
    {
        private BowlersDbContext _context { get; set; }

        public HomeController(BowlersDbContext temp)
        {
            _context = temp;
        }

        public IActionResult Index(string team)
        {
            ViewBag.SelectedTeam = RouteData?.Values["team"];

            var bowlers = _context.Bowlers
                .Where(x => x.Team.TeamName == team || team == null)
                .ToList();

            return View(bowlers);
        }
        

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Teams = _context.Teams.ToList();
            ViewBag.Id = 0;

            return View("Form");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Teams = _context.Teams.ToList();

            var bowler = _context.Bowlers.Single(x => x.BowlerID == id);
            ViewBag.Id = bowler.BowlerID;

            return View("Form", bowler);
        }

        [HttpPost]
        public IActionResult Form(Bowler b)
        {
            if (ModelState.IsValid)
            {
                if (b.BowlerID == 0)
                {
                    b.BowlerID = _context.Bowlers.ToList().LastOrDefault().BowlerID + 1;
                    _context.Bowlers.Add(b);
                }
                else
                {
                    _context.Bowlers.Update(b);
                }

                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Id = b.BowlerID;
                ViewBag.Teams = _context.Teams.ToList();

                return View();
            }
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var bowler = _context.Bowlers.Single(x => x.BowlerID == id);
            _context.Bowlers.Remove(bowler);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

BowlingLeagueApp/Views/Home/Form.cshtml
@{ 
    ViewData["Title"] = "Bowler Info";
}
@model BowlingLeagueApp.Models.Bowler

<h1>Bowler's Info</h1>

<div>
    <form method="post" asp-controller="Home" asp-action="Form">
        <div asp-validation-summary="All"></div>

        <input type="hidden" asp-for="BowlerID" value="@ViewBag.Id" />

        <label asp-for="BowlerFirstName">First Name:</label>
        <input asp-for="BowlerFirstName" /><br />

        <label asp-for="BowlerMiddleInit">Middle Initial:</label>
        <input asp-for="BowlerMiddleInit" /><br />

        <label asp-for="BowlerLastName">Last Name:</label>
        <input asp-for="BowlerLastName" /><br />

        <label asp-for="BowlerAddress">Address:</label>
        <input asp-for="BowlerAddress" /><br />

        <label asp-for="BowlerCity">City:</label>
        <input asp-for="BowlerCity" /><br />

        <label asp-for="BowlerState">State (ex: UT):</label>
        <input asp-for="BowlerState" /><br />

        <label asp-for="BowlerZip">Zipcode:</label>
        <input asp-for="BowlerZip" /><br />

        <label asp-for="BowlerPhoneNumber">Phone Number (ex: (801) 222-2222):</label>
        <input asp-for="BowlerPhoneNumber" /><br />
        
        <label asp-for="TeamID">Team:</label>
        <select asp-for="TeamID">
            <option value="">Select Team</option>
            @foreach (Team t in ViewBag.Teams)
            {
            <option value="@t.TeamID">@t.TeamName</option>
            }
        </select><br />

        <button type="submit">Submit Bowler Info</button>
    </form>
</div>

BowlingLeagueApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model List<Bowler>


<h1>@(ViewBag.SelectedTeam != null ? ViewBag.SelectedTeam : "All Teams")</h1>
<a class="btn btn-success" asp-controller="Home" asp-action="Add">Add New Bowler</a>
<br />
<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Middle Initial</th>
            <th>Last Name</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Zip</th>
            <th>Phone Number</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var b in Model)
        {
        <tr>
            <td>@b.BowlerFirstName</td>
            <td>@b.BowlerMiddleInit</td>
            <td>@b.BowlerLastName</td>
            <td>@b.BowlerAddress</td>
            <td>@b.BowlerCity</td>
            <td>@b.BowlerState</td>
            <td>@b.BowlerZip</td>
            <td>@b.BowlerPhoneNumber</td>

            <td><a asp-controller="Home" asp-action="Edit" asp-route-id="@b.BowlerID" class="btn btn-warning">Edit</a></td>
            <td>
                <form type="post" asp-controller="Home" asp-action="Delete">
                    <input type="hidden" id="id" name="id" value="@b.BowlerID" />
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        }
    </tbody>
</table>

BowlingLeagueApp/Views/Shared/Components/Teams/Default.cshtml
@{
}

@model IEnumerable<string>

<div class="d-grid gap-2">
    <a asp-controller="Home" asp-action="Index" asp-route-team="" class="btn btn-outline-secondary">Home</a>
    <br />

    @foreach (string t in Model)
    {
        <a asp-controller="Home" asp-action="Index" asp-route-team="@t"
           name="teamFilter" class="btn @(ViewBag.SelectedTeam == t ? "btn-primary" : "btn-outline-secondary")">@t</a>
        <br />
    }
</div>

BowlingLeagueApp/Views/Shared/_Layout.cshtml
@addTagHelper *, BowlingLeagueApp
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BowlingLeagueApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BowlingLeagueApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div class="row m-1 p-1">
            <div id="teams" class="col-3">
                <vc:teams></vc:teams>
            </div>
            <div class="col-9">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BowlingLeagueApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>